name: "Javan Cook"
description: "Webpage"

url: "http://javancook.com"

paginate: 10

markdown: redcarpet
redcarpet:
  extensions: ["tables", "strikethrough"]

permalink: /:year/:title/
highlighter: pygments
